import { NoteResume } from "../interfaces";

const words = [ "testing", "result", "batch", "error", "updating", "cancel", "how", "fix"]
const categories = [ "C#", "MongoDB", "PostgreSQL", "NextJS", "Go" ]

export async function deleteNotes(notes: NoteResume[]) {
   for (let index = 0; index < notes.length; index++) {
      const note = notes[index];
      await fetch(`/api/notes/${note.id}`, {
         method: 'DELETE'
      });
   }
}

export async function generateTestData() {
   for (let index = 0; index < 15; index++) {
      const title = generateRandomText();
      const exceptionMessage = generateRandomText();
      const tags = generateRandomCategories();
      
      var body = JSON.stringify({
         title,
         categories: tags,
         exceptionMessage,
         content: 'generated by test function'
      })

      await fetch('/api/notes/create', {
         method: 'POST',
         body
      })
   }
}

function generateRandomText() {
   // Pick a random word from the array, except the last index, to create at least a 3 words title
   let titleSeed = Math.floor(Math.random() * (words.length - 2));
   let title = words.slice(titleSeed, words.length).join(' ');
   let formattedTitle = title.charAt(0).toUpperCase() + title.slice(1);

   return formattedTitle;
}

function generateRandomCategories() {
   // Pick a random tag from the array, except the last index, to create at least 2 tags
   let seed = Math.floor(Math.random() * (categories.length - 1));
   return categories.slice(seed, categories.length);
}