import Head from 'next/head'
import Link from 'next/link'
import Footer from '../components/footer'
import Navbar from '../components/navbar'
import { NoteResume } from '../interfaces'
import useSwr from 'swr'
import styles from '../styles/Home.module.css'
import { useNote } from '../contexts/note'
import { useEffect } from 'react'
import CardsView from '../components/notesViews/cardsView'
import { useView } from '../contexts/view'
import ListView from '../components/notesViews/listView'
import Filter from '../components/filter'

const fetcher = (url: string) => fetch(url).then((res) => res.json())

export default function Home() {
  const { data, error } = useSwr<NoteResume[]>('/api/notes', fetcher)
  const { summaryNotes, setSummaryNotes } = useNote()
  const { view } = useView()

  useEffect(() => {
    if (data)
      setSummaryNotes(data)
  }, [data])

  useEffect(() => {
  }, [summaryNotes])

  if (error) return <div>Failed to load users</div>
  if (!data) return <div>Loading...</div>

  function pickView(data: NoteResume[]) {
    switch (view) {
      case "Card":
        return (<CardsView data={data} />)

      case "List":
        return (<ListView />)
    
      default:
        return (null);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          {summaryNotes.length} vaults
        </h1>

        {/* Botão de novo */}
        <div className='d-grid gap-2 col-2'>
          <Link href="/new" className='mx-auto my-4 mb-2'>
            <button className="btn btn-outline-success btn-lg" type="button">Novo</button>
          </Link>
        </div>
        
        <Filter />

        { pickView(data) }

      </main>

      <Footer />
    </div>
  )
}
