import Head from 'next/head'
import Link from 'next/link'
import Footer from '../components/footer'
import Navbar from '../components/navbar'
import { NoteResume } from '../interfaces'
import useSwr from 'swr'
import styles from '../styles/Home.module.css'

const fetcher = (url: string) => fetch(url).then((res) => res.json())

export default function Home() {
  const { data, error } = useSwr<NoteResume[]>('/api/notes', fetcher)

  if (error) return <div>Failed to load users</div>
  if (!data) return <div>Loading...</div>

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          {data.length} vaults
        </h1>

        {/* Botão de novo */}
        <Link href="/new" className="d-grid gap-2 col-2 mx-auto my-4">
          <button className="btn btn-outline-success btn-lg" type="button">Novo</button>
        </Link>

        <div className={styles.grid}>
          {data.map((note) => {
            return (
              <Link key={note.id} href="/note/[id]" as={`/note/${note.id}`} className={styles.card}>
                <h2>{note.title} &rarr;</h2>
                <p>{note.exceptionMessage}</p>
                <div>
                  {note.categories?.map((category) => {
                    return (
                      <span key={category} className="badge text-bg-dark p-2 m-1">
                        {category}
                      </span>
                    )
                  })}
              </div>
              </Link>
            )
          })}
        </div>
      </main>

      <Footer />
    </div>
  )
}
